# We set the language to python, even if we use compiled extensions.
language: python

# The python versions to test.
python:
    - 3.4
    - 3.6
    - 3.7

before_install:
    # Install binary python dependencies.
    - pip3 install -q numpy matplotlib toml quaternionarray

# Install sotodlib
install:
    - python3 setup.py install

# Run tests.  Disable plot output which can be time-consuming.
script:
    - export SOTODLIB_TEST_DISABLE_PLOTS=1
    - python3 setup.py test
