DEPTH1MAPMAKER_DEFAULTS = {
    "query": "1",
    "odir": "./outputs",
    "comps": "T",
    "ntod": None,
    "tods": None,
    "nset": None,
    "site": "so_lat",
    "nmat": "corr",
    "max_dets": None,
    "verbose": 0,
    "quiet": 0,
    "center_at": None,
    "window": 0.0,
    "nmat_dir": "/nmats",
    "nmat_mode": "build",
    "downsample": 1,
    "maxiter": 100,
    "tiled": 1,
    "wafer": None,
    "freq": None,
    "tasks_per_group": 1,
    "cont": False,
    "rhs": False,
    "bin": False,
    "srcsamp": None,
    "unit": "K",
    "mapcat_database_type": "sqlite",
    "mapcat_database_name": "mapcat.db",
    "mapcat_depth_one_parent": "./",
    "min_dets": 50,
}

SENS_LIMITS = {
    "f030": 120,
    "f040": 80,
    "f090": 100,
    "f150": 140,
    "f220": 300,
    "f280": 750,
}