.. code-block:: console

    usage: so_hardware_sim [options] (use --help for details)

    This program simulates the current nominal hardware model and dumps it to disk

    optional arguments:
      -h, --help   show this help message and exit
      --out OUT    Name (without extensions) of the output hardware file
      --plain      Write plain text (without gzip compression)
      --overwrite  Overwrite any existing output file.
